version: '3.8'

services:
  yer-wallet-backend:
    build: .
    container_name: yer_wallet_core
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PI_NETWORK_ENVIRONMENT=mainnet
    depends_on:
      - yer-db
    restart: always

  yer-db:
    image: postgres:15-alpine
    container_name: yer_wallet_db
    environment:
      - POSTGRES_DB=bigish_yer_db
      - POSTGRES_USER=yer_governor
      - POSTGRES_PASSWORD=secure_political_passphrase_137
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
